# Generated by Django 6.0.4 on 2026-06-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_pedido_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_legada',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
